<?php
/* 
 * Generated by CRUDigniter v1.3 Beta 
 * www.crudigniter.com
 */
 
class PROVINSI extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('PROVINSI_model');
    }
    
    /*
     * Listing of PROVINSI
     */
    function index()
    {
        $data['provinsi'] = $this->PROVINSI_model->get_all_PROVINSI();
        $this->load->view('PROVINSI/index',$data);
    }
    
    /*
     * Adding new PROVINSI
     */
    function add()
    {   
        $this->load->library('form_validation');

        $this->form_validation->set_rules('PROVINSI_NAMA','PROVINSI NAMA','required|max_length[255]');
        
        if($this->form_validation->run())     
        {   
            $params = array(
                'PROVINSI_NAMA' => $this->input->post('PROVINSI_NAMA'),
            );
            
            $PROVINSI_id = $this->PROVINSI_model->add_PROVINSI($params);
            redirect('provinsi/index');
        }
        else
        {
            $this->load->view('PROVINSI/add');
        }
    }
    
    /*
     * Editing PROVINSI
     */
    function edit($PROVINSI_KODE)
    {   
        $this->load->library('form_validation');

        $this->form_validation->set_rules('PROVINSI_KODE','PROVINSI _NAMA');
        
        if($this->form_validation->run())     
        {   
            $params = array(
                'PROVINSI_KODE' => $this->input->post('PROVINSI_KODE'),
            );

            $this->PROVINSI_model->update_PROVINSI($PROVINSI_KODE,$params);            
            redirect('provinsi/index');
        }
       else
        {   
            $params['PROVINSI'] = $this->PROVINSI_model->get_PROVINSI($PROVINSI_KODE);
            $this->load->view('PROVINSI/edit',$params);
        }
    }
    
    /*
     * Deleting PROVINSI
     */
    function remove($PROVINSI_KODE)
    {
        $this->PROVINSI_model->delete_PROVINSI($PROVINSI_KODE);
        redirect('provinsi/index');
    }
}
