<?php
/* 
 * Generated by CRUDigniter v1.3 Beta 
 * www.crudigniter.com
 */
 
class PROVINSI_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * get PROVINSI by PROVINSI_KODE
     */
    function get_PROVINSI($PROVINSI_KODE)
    {
        return $this->db->get_where('PROVINSI',array('PROVINSI_KODE'=>$PROVINSI_KODE))->row_array();
    }
    
    /*
     * get all PROVINSI
     */
    function get_all_PROVINSI()
    {
        return $this->db->get('PROVINSI')->result_array();
    }
    
    /*
     * function to add PROVINSI
     */
    function add_PROVINSI($params)
    {
        $this->db->insert('PROVINSI',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update PROVINSI
     */
    function update_PROVINSI($PROVINSI_KODE,$params)
    {
        $this->db->where('PROVINSI_KODE',$id);
        $this->db->update('PROVINSI',$params);
    }
    
    /*
     * function to delete PROVINSI
     */
    function delete_PROVINSI($PROVINSI_KODE)
    {
        $this->db->delete('PROVINSI',array('PROVINSI_KODE'=>$PROVINSI_KODE));
    }
}
